CREATE DATABASE WMS;

CREATE TABLE Clients(
ClientId INT PRIMARY KEY IDENTITY NOT NULL,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Phone CHAR(12) CHECK (LEN(Phone)=12) NOT NULL
)

CREATE TABLE Mechanics(
MechanicId INT PRIMARY KEY IDENTITY NOT NULL,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Address VARCHAR(255) NOT NULL
)

CREATE TABLE Models(
ModelId INT PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(50) NOT NULL UNIQUE,
)

CREATE TABLE Jobs(
JobId INT PRIMARY KEY IDENTITY NOT NULL,
ModelId INT NOT NULL FOREIGN KEY REFERENCES Models(ModelId),
[Status] VARCHAR(11) NOT NULL CHECK ([Status] IN ('Pending', 'In Progress', 'Finished')) DEFAULT 'Pending',
ClientId INT NOT NULL FOREIGN KEY REFERENCES Clients(ClientId),
MechanicId INT FOREIGN KEY REFERENCES Mechanics(MechanicId),
IssueDate DATE NOT NULL,
FinishDate DATE 
)

CREATE TABLE Orders(
OrderId INT PRIMARY KEY IDENTITY NOT NULL,
JobId INT NOT NULL FOREIGN KEY REFERENCES Jobs(JobId),
IssueDate DATE ,
Delivered BIT DEFAULT 0
)

CREATE TABLE Vendors(
VendorId INT PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE Parts(
PartId INT PRIMARY KEY IDENTITY NOT NULL,
SerialNumber VARCHAR(50) NOT NULL UNIQUE,
Description VARCHAR(255) ,
Price DECIMAL(15,2) NOT NULL CHECK (Price > 0 AND Price < 9999.99),
VendorId INT FOREIGN KEY REFERENCES Vendors(VendorId),
StockQty INT NOT NULL CHECK (StockQty >=0) DEFAULT 0
)

CREATE TABLE OrderParts(
OrderId INT FOREIGN KEY REFERENCES Orders(OrderId) NOT NULL,
PartId INT FOREIGN KEY REFERENCES Parts(PartId) NOT NULL,
Quantity INT CHECK (Quantity>0) DEFAULT 1,
PRIMARY KEY(OrderId,PartId)
)


CREATE TABLE PartsNeeded(
JobId INT FOREIGN KEY REFERENCES Jobs(JobId) NOT NULL,
PartId INT FOREIGN KEY REFERENCES Parts(PartId) NOT NULL,
Quantity INT CHECK (Quantity>0) DEFAULT 1,
PRIMARY KEY (JobId,PartId)
)




